version: "3.8"
services:
  # rabbitmq:
  #   image: rabbitmq:3.8-management-alpine
  #   container_name: 'rabbitmq'
  #   ports:
  #       - 5673:5672
  #       - 15673:15672
  #   volumes:
  #       - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
  #       - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  #   networks:
  #       - rabbitmq_nodejs
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  # consumer:
  #   build:
  #     context: ./
  #     target: dev
  #   volumes:
  #     - .:/src
  #   depends_on:
  #     - "rabbitmq"
  #   command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node consumer.js'
  #   environment:
  #     NODE_ENV: production
  #     AMQP_URL: amqp://guest:guest@rabbitmq:5672
  #   networks:
  #     - rabbitmq_nodejs
networks:
  rabbitmq_nodejs:
    driver: bridge
